#!/bin/sh

browserify () {
	../node_modules/.bin/browserify $@
}

# $1 - Output file
# $2-- Input fules
compile () {
	out=$1
	shift
	files=$@
	browserify $files -o $out
}

compile runtime/simple_worker.js simple_worker.js
